[bar]
order = [ "default" ]

    [bar.default]
    thickness = 45
    scale = 1.10
    margin_edge = 10
    margin_ends = 10
    radius = 20
    background_opacity = 0.93
    capsule = true
    end = [ "recorder", "tray", "network", "bluetooth", "notifications", "volume", "brightness", "battery", "control-center" ]
    shadow = true
    start = [ "workspaces", "active_window", "media" ]

[brightness]
enable_ddcutil = true

[desktop_widgets]
enabled = false

[idle]
pre_action_fade_seconds = 5
behavior_order = [ "lock", "screen-off", "suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660

    [idle.behavior.suspend]
    action = "suspend"
    enabled = false
    lock_before_suspend = true
    timeout = 900

[shell]
avatar_path = "/var/lib/AccountsService/icons/yuzujr"
font_family = "Noto Sans CJK SC"
polkit_agent = true
settings_show_advanced = false
clipboard_auto_paste = "off"
    
    [shell.panel]
    open_near_click_control_center = true
    launcher_categories = false
    launcher_session_search = true
    transparency_mode = "soft"
    
    [shell.shadow]
    blur = 12

[system.monitor]
enabled = false

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/translator" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[theme]
builtin = "Rosé Pine"
mode = "auto"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "yazi" ]

[wallpaper]
directory = "/home/yuzujr/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/yuzujr/Pictures/Wallpapers/7.png"

    [wallpaper.last]
    path = "/home/yuzujr/Pictures/Wallpapers/7.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/yuzujr/Pictures/Wallpapers/7.png"

[weather]
enabled = true

[widget.workspaces]
display = "none"
empty_color = "on_surface"
occupied_color = "on_surface"

[widget.active_window]
show_empty_label = true
icon_size = 18.0
min_length = 0.0
max_length = 200.0
title_scroll = "on_hover"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.tray]
drawer = true

[widget.brightness]
show_label = false

[widget.network]
show_label = false

[widget.volume]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[[control_center.shortcuts]]
type = "wifi"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "dark_mode"

[backdrop]
enabled = true

[location]
address = "Shenzhen, CN"

[notification]
background_opacity = 0.93

[osd]
background_opacity = 0.93
lock_keys = false
position = "top_right"

